/**
 * Request and response type definitions for the OpenWA API.
 *
 * IMPORTANT (hybrid codegen strategy): this module is the single source of truth
 * for wire types. It is the part most prone to drift with the backend, and is
 * structured so that it can be regenerated by an OpenAPI codegen pass later
 * without touching the hand-written resource methods (paths + DX live elsewhere).
 *
 * Field names mirror the backend DTOs exactly (camelCase JSON).
 *
 * @packageDocumentation
 */

// ── Common ────────────────────────────────────────────────────────

/** A WhatsApp JID, e.g. `628123456789@c.us` (user) or `120363…@g.us` (group). */
export type Jid = string;

/** Session lifecycle status. */
export type SessionStatus =
  | 'created'
  | 'initializing'
  | 'qr_ready'
  | 'authenticating'
  | 'ready'
  | 'disconnected'
  | 'failed';

/** Minimal success envelope returned by some state-changing endpoints. */
export interface SuccessResult {
  success: boolean;
  message?: string;
}

// ── Session ───────────────────────────────────────────────────────

export interface SessionResponse {
  id: string;
  name: string;
  status: SessionStatus;
  phone?: string | null;
  pushName?: string | null;
  connectedAt?: string | null;
  lastActive?: string | null;
  createdAt: string;
  updatedAt: string;
  /** Only present when `status === 'failed'`. */
  lastError?: string | null;
}

export interface CreateSessionRequest {
  /** Alphanumeric + hyphens, 3–50 chars. */
  name: string;
  config?: Record<string, unknown>;
  proxyUrl?: string;
  proxyType?: 'http' | 'https' | 'socks4' | 'socks5';
}

export interface QrCodeResponse {
  /** Data URL, e.g. `data:image/png;base64,…`. */
  qrCode: string;
  status: SessionStatus;
}

export interface PairingCodeResponse {
  /** 8-character code, e.g. `ABCD1234`. */
  pairingCode: string;
  status: string;
}

export interface RequestPairingCodeRequest {
  /** Digits only, international format, e.g. `628123456789`. */
  phoneNumber: string;
}

export interface SessionStatsOverview {
  total: number;
  active: number;
  ready: number;
  disconnected: number;
  byStatus: Record<string, number>;
  memoryUsage?: { heapUsed: number; heapTotal: number; rss: number };
}

// ── Message ───────────────────────────────────────────────────────

/** Returned by every send operation. */
export interface MessageResponse {
  messageId: string;
  /** Unix timestamp in milliseconds. */
  timestamp: number;
}

export interface SendTextRequest {
  chatId: Jid;
  /** Max 4096 chars. */
  text: string;
}

export interface SendMediaRequest {
  chatId: Jid;
  /** Mutually exclusive with `base64`. */
  url?: string;
  /** Requires `mimetype`. */
  base64?: string;
  mimetype?: string;
  /** Required for documents; max 255 chars. */
  filename?: string;
  /** Max 1024 chars. */
  caption?: string;
}

export interface SendLocationRequest {
  chatId: Jid;
  latitude: number;
  longitude: number;
  description?: string;
  address?: string;
}

export interface SendContactRequest {
  chatId: Jid;
  contactName: string;
  contactNumber: string;
}

export interface ReplyMessageRequest {
  chatId: Jid;
  quotedMessageId: string;
  text: string;
}

export interface ForwardMessageRequest {
  fromChatId: Jid;
  toChatId: Jid;
  messageId: string;
}

export interface ReactMessageRequest {
  chatId: Jid;
  messageId: string;
  /** Empty string removes the reaction. */
  emoji: string;
}

export interface DeleteMessageRequest {
  chatId: Jid;
  messageId: string;
  /** Delete for everyone (default true). */
  forEveryone?: boolean;
}

export interface SendTemplateRequest {
  chatId: Jid;
  /** Provide exactly one of `templateId` or `templateName`. */
  templateId?: string;
  /** Provide exactly one of `templateId` or `templateName`. */
  templateName?: string;
  /** Template variables (server DTO field is `vars`). */
  vars?: Record<string, string>;
}

export interface ListMessagesQuery {
  chatId?: Jid;
  from?: Jid;
  limit?: number;
  offset?: number;
}

export interface MessageHistoryQuery {
  limit?: number;
  includeMedia?: boolean;
  deep?: boolean;
}

/** Message direction. */
export type MessageDirection = 'incoming' | 'outgoing';

/** Delivery status for a message. */
export type DeliveryStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'failed';

/** A persisted message row, as returned by `GET /sessions/:id/messages`. */
export interface MessageRecord {
  id: string;
  sessionId: string;
  /** Engine/WhatsApp message id; may be null until a send is acked. */
  waMessageId?: string | null;
  chatId: Jid;
  from: Jid;
  to: Jid;
  body?: string | null;
  type: string;
  direction: MessageDirection;
  /** Unix timestamp in milliseconds. */
  timestamp?: number | null;
  metadata?: Record<string, unknown> | null;
  status: DeliveryStatus;
  createdAt: string;
}

/**
 * A message read live from WhatsApp by `messages.history()`. This is the engine
 * payload (richer and differently shaped than the persisted {@link MessageRecord}).
 */
export interface ChatHistoryMessage {
  id: string;
  from: Jid;
  to: Jid;
  chatId: Jid;
  body: string;
  type: string;
  /** Unix timestamp in seconds. */
  timestamp: number;
  fromMe: boolean;
  isGroup: boolean;
  isStatusBroadcast?: boolean;
  /** For group messages, the participant who sent it (`from` is the group JID). */
  author?: Jid;
  mentionedIds?: Jid[];
  isLidSender?: boolean;
  senderPhone?: string | null;
  media?: {
    mimetype: string;
    filename?: string;
    /** base64; absent when the payload was omitted (too large). */
    data?: string;
    omitted?: boolean;
    sizeBytes?: number;
  };
  quotedMessage?: { id: string; body: string };
  location?: { latitude: number; longitude: number; description?: string; address?: string; url?: string };
}

/** Paginated payload returned by `GET /sessions/:id/messages`. */
export interface MessageListResponse {
  messages: MessageRecord[];
  total: number;
}

export interface ReactionSender {
  senderId: Jid;
  emoji: string;
  /** Unix timestamp in seconds. */
  timestamp: number;
}

/** One emoji and everyone who reacted with it (server returns `MessageReaction[]`). */
export interface ReactionRecord {
  emoji: string;
  senders: ReactionSender[];
}

// ── Bulk ──────────────────────────────────────────────────────────

export type BulkMessageType = 'text' | 'image' | 'video' | 'audio' | 'document';

export interface BulkMessageContent {
  text?: string;
  image?: SendMediaRequest;
  video?: SendMediaRequest;
  audio?: SendMediaRequest;
  document?: SendMediaRequest;
  caption?: string;
}

export interface BulkMessageItem {
  chatId: Jid;
  type: BulkMessageType;
  content: BulkMessageContent;
  variables?: Record<string, string>;
}

export interface SendBulkRequest {
  messages: BulkMessageItem[];
  /** Optional caller-supplied idempotency/batch id. */
  batchId?: string;
  options?: {
    /** Minimum 1000 ms; default 3000. */
    delayBetweenMessages?: number;
    /** Randomize the delay between messages to look less automated. */
    randomizeDelay?: boolean;
    stopOnError?: boolean;
  };
}

export interface BulkMessageResponse {
  batchId: string;
  status: string;
  totalMessages: number;
  estimatedCompletionTime: string;
  statusUrl: string;
}

/** Progress counters for a bulk-send batch. */
export interface BatchProgress {
  total: number;
  sent: number;
  failed: number;
  pending: number;
  cancelled: number;
}

/** Per-message outcome within a batch result list. */
export interface BatchMessageResult {
  chatId?: Jid;
  status?: string;
  messageId?: string;
  sentAt?: string;
  error?: { code: string; message: string };
}

/**
 * Response from `GET /messages/batch/:batchId` (batch status polling) and
 * `POST /messages/batch/:batchId/cancel`. Distinct from
 * {@link BulkMessageResponse} (the send-bulk acknowledgement).
 */
export interface BatchStatusResponse {
  batchId: string;
  status: string;
  progress?: BatchProgress;
  results?: BatchMessageResult[];
  startedAt?: string;
  completedAt?: string;
}

// ── Contact ───────────────────────────────────────────────────────

export interface ContactRecord {
  id: Jid;
  name?: string | null;
  number?: string | null;
  pushname?: string | null;
  isBusiness?: boolean;
  isMyContact?: boolean;
}

export interface CheckNumberResponse {
  number: string;
  exists: boolean;
  whatsappId?: string | null;
}

export interface ProfilePictureResponse {
  url: string | null;
}

export interface ContactPhoneResponse {
  contactId: Jid;
  phone: string | null;
}

// ── Group ─────────────────────────────────────────────────────────

export interface GroupParticipant {
  id: Jid;
  number: string;
  name?: string;
  isAdmin: boolean;
  isSuperAdmin: boolean;
}

/** Item returned by `GET /sessions/:id/groups` (the slim list shape). */
export interface GroupSummary {
  id: Jid;
  name: string;
  participantsCount?: number;
  isAdmin?: boolean;
  /** JID of the parent community, or null if standalone. */
  linkedParentJID?: string | null;
}

/** Full detail returned by `GET /sessions/:id/groups/:groupId`. */
export interface GroupInfo {
  id: Jid;
  name: string;
  description?: string | null;
  owner?: Jid | null;
  /** Unix timestamp in seconds. */
  createdAt?: number;
  participants: GroupParticipant[];
  isReadOnly?: boolean;
  isAnnounce?: boolean;
  linkedParentJID?: string | null;
}

export interface CreateGroupRequest {
  name: string;
  participants: Jid[];
}

export interface ParticipantsRequest {
  participants: Jid[];
}

export interface GroupSubjectRequest {
  subject: string;
}

export interface GroupDescriptionRequest {
  /** May be empty to clear. */
  description: string;
}

export interface InviteCodeResponse {
  inviteCode: string;
  inviteLink: string;
  message?: string;
}

// ── Webhook ───────────────────────────────────────────────────────

/** Events a webhook may subscribe to. Use `*` to receive all. */
export type WebhookEvent =
  | 'message.received'
  | 'message.sent'
  | 'message.ack'
  | 'message.failed'
  | 'message.revoked'
  | 'message.reaction'
  | 'session.status'
  | 'session.qr'
  | 'session.authenticated'
  | 'session.disconnected'
  // Reserved: accepted on subscribe but not dispatched yet.
  | 'group.join'
  | 'group.leave'
  | 'group.update'
  | '*';

export interface WebhookFilterCondition {
  field: string;
  operator: string;
  value: string[];
}

export interface WebhookFilters {
  conditions: WebhookFilterCondition[];
}

export interface CreateWebhookRequest {
  url: string;
  events?: WebhookEvent[];
  /** HMAC secret; signed as `X-OpenWA-Signature: sha256=…`. */
  secret?: string;
  headers?: Record<string, string>;
  filters?: WebhookFilters | null;
  /** 0–5; default 3. Server DTO field is `retryCount`. */
  retryCount?: number;
}

export type UpdateWebhookRequest = Partial<CreateWebhookRequest> & { active?: boolean };

export interface WebhookResponse {
  id: string;
  sessionId: string;
  url: string;
  events: WebhookEvent[];
  active: boolean;
  filters?: WebhookFilters | null;
  retryCount: number;
  /** ISO timestamp of the last delivery attempt, or null if never triggered. */
  lastTriggeredAt: string | null;
  createdAt: string;
  updatedAt: string;
  // NOTE: the server deliberately omits `secret` and `headers` from read responses.
}

export interface WebhookTestResult {
  success: boolean;
  statusCode?: number;
  error?: string;
}

// ── Chat (session-scoped chat operations) ─────────────────────────

export interface ChatSummary {
  id: Jid;
  name?: string | null;
  isGroup?: boolean;
  unreadCount?: number;
  /** Preview text of the last message (the server returns a plain string, not an object). */
  lastMessage?: string;
  timestamp?: string | number;
}

export interface MarkChatRequest {
  chatId: Jid;
}

export type ChatState = 'typing' | 'recording' | 'paused';

export interface SendChatStateRequest {
  chatId: Jid;
  state: ChatState;
}

export interface DeleteChatRequest {
  chatId: Jid;
}

// ── Status / Stories ──────────────────────────────────────────────

export interface StatusRecord {
  id?: string;
  statusId?: string;
  type?: string;
  body?: string | null;
  timestamp?: string | number;
}

export interface SendTextStatusRequest {
  text: string;
  /** Hex background color, e.g. `#25D366`. */
  backgroundColor?: string;
  /** Font index supported by WhatsApp status. */
  font?: number;
}

/** Media payload for a status post: provide `url` OR `base64`. */
export interface StatusMediaInput {
  url?: string;
  base64?: string;
}

/** Server expects a nested `{ image: { url|base64 } }` body, not flat media fields. */
export interface SendImageStatusRequest {
  image: StatusMediaInput;
  caption?: string;
}

/** Server expects a nested `{ video: { url|base64 } }` body, not flat media fields. */
export interface SendVideoStatusRequest {
  video: StatusMediaInput;
  caption?: string;
}

// ── Health ────────────────────────────────────────────────────────

export interface HealthResponse {
  status: string;
  timestamp?: string;
  version?: string;
}

export interface HealthReadyDetails {
  mainDatabase?: string;
  dataDatabase?: string;
}

export interface HealthReadyResponse {
  status: string;
  details?: HealthReadyDetails;
}

// ── Auth ──────────────────────────────────────────────────────────

export interface AuthValidateResponse {
  valid: boolean;
  role?: string;
}

// ── Template ──────────────────────────────────────────────────────

export interface TemplateRecord {
  id: string;
  sessionId: string;
  name: string;
  /** Template body with `{{variable}}` placeholders. */
  body: string;
  header?: string | null;
  footer?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTemplateRequest {
  /** Unique template name within the session. */
  name: string;
  body: string;
  header?: string;
  footer?: string;
}

export type UpdateTemplateRequest = Partial<CreateTemplateRequest>;

// ── Label (WhatsApp Business) ─────────────────────────────────────

export interface LabelRecord {
  id: string;
  name: string;
  color?: string;
  colorHex?: string;
}

export interface AddLabelRequest {
  labelId: string;
}

// ── Channel / Newsletter ──────────────────────────────────────────

export interface ChannelRecord {
  id: Jid;
  name?: string;
  description?: string | null;
  subscriberCount?: number;
  pictureUrl?: string | null;
  role?: string;
}

export interface ChannelMessageQuery {
  /** Max messages to return (default 50). */
  limit?: number;
}

export interface SubscribeChannelRequest {
  /** Channel invite code (from a channel link). */
  inviteCode: string;
}

// ── Catalog (Business) ────────────────────────────────────────────

export interface CatalogInfo {
  id: string;
  name: string;
  description?: string | null;
  productCount: number;
  url: string;
}

export interface CatalogProductsQuery {
  /** Page number (min 1, default 1). */
  page?: number;
  /** Page size (min 1, default 20). */
  limit?: number;
}

export interface CatalogProduct {
  id: string;
  name: string;
  description?: string | null;
  price: number;
  currency: string;
  priceFormatted: string;
  imageUrl?: string | null;
  url: string;
  isAvailable: boolean;
  retailerId?: string;
}

/** Paginated payload returned by `GET /sessions/:id/catalog/products`. */
export interface PaginatedProducts {
  products: CatalogProduct[];
  pagination: { page: number; limit: number; total: number; totalPages: number };
}

export interface SendProductRequest {
  chatId: Jid;
  productId: string;
  /** Optional body/caption text. */
  body?: string;
}

export interface SendCatalogRequest {
  chatId: Jid;
  /** Optional body/caption text. */
  body?: string;
}
