"""Wire type definitions for the OpenWA API.

Hybrid codegen strategy: this module is the single source of truth for wire
types — the part most prone to drift with the backend. It is structured so it
can be regenerated by an OpenAPI codegen pass later without touching the
hand-written resource methods (paths + DX live elsewhere).

Field names mirror the backend DTOs exactly (camelCase JSON).
"""

from __future__ import annotations

from typing import Any, Literal, Optional, TypedDict

Jid = str
SessionStatus = Literal[
    "created", "initializing", "qr_ready", "authenticating", "ready", "disconnected", "failed"
]
ChatState = Literal["typing", "recording", "paused"]
MessageDirection = Literal["incoming", "outgoing"]
DeliveryStatus = Literal["pending", "sent", "delivered", "read", "failed"]
BulkMessageType = Literal["text", "image", "video", "audio", "document"]
WebhookEvent = Literal[
    "message.received", "message.sent", "message.ack", "message.failed", "message.revoked",
    "message.reaction", "session.status", "session.qr", "session.authenticated",
    "session.disconnected",
    # Reserved: accepted on subscribe but not dispatched yet.
    "group.join", "group.leave", "group.update",
    "*",
]


class SuccessResult(TypedDict, total=False):
    success: bool
    message: str


# ── Session ───────────────────────────────────────────────────────


class SessionResponse(TypedDict, total=False):
    id: str
    name: str
    status: SessionStatus
    phone: str | None
    pushName: str | None
    connectedAt: str | None
    lastActive: str | None
    createdAt: str
    updatedAt: str
    lastError: str | None


class CreateSessionRequest(TypedDict, total=False):
    name: str
    config: dict[str, Any]
    proxyUrl: str
    proxyType: Literal["http", "https", "socks4", "socks5"]


class QrCodeResponse(TypedDict):
    qrCode: str
    status: SessionStatus


class PairingCodeResponse(TypedDict):
    pairingCode: str
    status: str


class RequestPairingCodeRequest(TypedDict):
    phoneNumber: str


class MemoryUsage(TypedDict):
    heapUsed: int
    heapTotal: int
    rss: int


class SessionStatsOverview(TypedDict, total=False):
    total: int
    active: int
    ready: int
    disconnected: int
    byStatus: dict[str, int]
    memoryUsage: MemoryUsage


# ── Message ───────────────────────────────────────────────────────


class MessageResponse(TypedDict):
    messageId: str
    timestamp: int


class SendTextRequest(TypedDict):
    chatId: Jid
    text: str


class SendMediaRequest(TypedDict, total=False):
    chatId: Jid
    url: str
    base64: str
    mimetype: str
    filename: str
    caption: str


class SendLocationRequest(TypedDict, total=False):
    # chatId/latitude/longitude required; description/address optional.
    chatId: Jid
    latitude: float
    longitude: float
    description: str
    address: str


class SendContactRequest(TypedDict):
    chatId: Jid
    contactName: str
    contactNumber: str


class ReplyMessageRequest(TypedDict):
    chatId: Jid
    quotedMessageId: str
    text: str


class ForwardMessageRequest(TypedDict):
    fromChatId: Jid
    toChatId: Jid
    messageId: str


class ReactMessageRequest(TypedDict):
    chatId: Jid
    messageId: str
    emoji: str


class DeleteMessageRequest(TypedDict, total=False):
    # chatId/messageId required; forEveryone optional (default true).
    chatId: Jid
    messageId: str
    forEveryone: bool


class SendTemplateRequest(TypedDict, total=False):
    # chatId required; provide exactly one of templateId / templateName.
    # Modeled total=False (callers pass plain dicts); the backend validates.
    chatId: Jid
    templateId: str
    templateName: str
    vars: dict[str, str]


# ``from`` is a Python keyword, so use the functional TypedDict form.
ListMessagesQuery = TypedDict(
    "ListMessagesQuery",
    {"chatId": Jid, "from": Jid, "limit": int, "offset": int},
    total=False,
)


class MessageHistoryQuery(TypedDict, total=False):
    limit: int
    includeMedia: bool
    deep: bool


# ``from`` is a Python keyword, so use the functional TypedDict form (and
# Optional[...] rather than ``X | None`` so the runtime values stay 3.9-safe).
MessageRecord = TypedDict(
    "MessageRecord",
    {
        "id": str,
        "sessionId": str,
        "waMessageId": Optional[str],
        "chatId": Jid,
        "from": Jid,
        "to": Jid,
        "body": Optional[str],
        "type": str,
        "direction": MessageDirection,
        "timestamp": Optional[int],
        "metadata": dict,
        "status": DeliveryStatus,
        "createdAt": str,
    },
    total=False,
)


class ChatHistoryMedia(TypedDict, total=False):
    mimetype: str
    filename: str
    data: str  # base64; absent when the payload was omitted (too large)
    omitted: bool
    sizeBytes: int


class QuotedMessage(TypedDict, total=False):
    id: str
    body: str


class MessageLocation(TypedDict, total=False):
    latitude: float
    longitude: float
    description: str
    address: str
    url: str


# A message read live from WhatsApp by ``messages.history()`` — the engine
# payload, richer and differently shaped than the persisted MessageRecord.
ChatHistoryMessage = TypedDict(
    "ChatHistoryMessage",
    {
        "id": str,
        "from": Jid,
        "to": Jid,
        "chatId": Jid,
        "body": str,
        "type": str,
        "timestamp": int,
        "fromMe": bool,
        "isGroup": bool,
        "isStatusBroadcast": bool,
        "author": Jid,
        "mentionedIds": list,
        "isLidSender": bool,
        "senderPhone": Optional[str],
        "media": ChatHistoryMedia,
        "quotedMessage": QuotedMessage,
        "location": MessageLocation,
    },
    total=False,
)


class MessageListResponse(TypedDict):
    """Paginated payload returned by ``GET /sessions/:id/messages``."""

    messages: list[MessageRecord]
    total: int


class ReactionSender(TypedDict, total=False):
    senderId: Jid
    emoji: str
    timestamp: int


class ReactionRecord(TypedDict, total=False):
    """One emoji and everyone who reacted with it (server returns MessageReaction[])."""

    emoji: str
    senders: list[ReactionSender]


# ── Bulk ──────────────────────────────────────────────────────────


class BulkMessageContent(TypedDict, total=False):
    text: str
    image: SendMediaRequest
    video: SendMediaRequest
    audio: SendMediaRequest
    document: SendMediaRequest
    caption: str


class BulkMessageItem(TypedDict, total=False):
    # chatId/type/content required; variables optional.
    chatId: Jid
    type: BulkMessageType
    content: BulkMessageContent
    variables: dict[str, str]


class BulkOptions(TypedDict, total=False):
    delayBetweenMessages: int
    randomizeDelay: bool
    stopOnError: bool


class _SendBulkRequired(TypedDict):
    messages: list[BulkMessageItem]


class SendBulkRequest(_SendBulkRequired, total=False):
    # `options` and `batchId` are optional; the backend applies defaults.
    options: BulkOptions
    batchId: str


class BulkMessageResponse(TypedDict):
    batchId: str
    status: str
    totalMessages: int
    estimatedCompletionTime: str
    statusUrl: str


class BatchError(TypedDict, total=False):
    code: str
    message: str


class BatchMessageResult(TypedDict, total=False):
    chatId: Jid
    status: str
    messageId: str
    sentAt: str
    error: BatchError


class BatchProgress(TypedDict, total=False):
    total: int
    sent: int
    failed: int
    pending: int
    cancelled: int


class BatchStatusResponse(TypedDict, total=False):
    """Response from ``GET /messages/batch/:batchId`` and the cancel endpoint.

    Distinct from :class:`BulkMessageResponse` (the send-bulk acknowledgement).
    """

    batchId: str
    status: str
    progress: BatchProgress
    results: list[BatchMessageResult]
    startedAt: str
    completedAt: str


# ── Contact ───────────────────────────────────────────────────────


class ContactRecord(TypedDict, total=False):
    id: Jid
    name: str | None
    number: str | None
    pushname: str | None
    isBusiness: bool
    isMyContact: bool


class CheckNumberResponse(TypedDict):
    number: str
    exists: bool
    whatsappId: str | None


class ProfilePictureResponse(TypedDict):
    url: str | None


class ContactPhoneResponse(TypedDict):
    contactId: Jid
    phone: str | None


# ── Group ─────────────────────────────────────────────────────────


class GroupParticipant(TypedDict, total=False):
    id: Jid
    number: str
    name: str
    isAdmin: bool
    isSuperAdmin: bool


class GroupSummary(TypedDict, total=False):
    """Item returned by ``GET /sessions/:id/groups`` (the slim list shape)."""

    id: Jid
    name: str
    participantsCount: int
    isAdmin: bool
    linkedParentJID: str | None


class GroupInfo(TypedDict, total=False):
    """Full detail returned by ``GET /sessions/:id/groups/:groupId``."""

    id: Jid
    name: str
    description: str | None
    owner: Jid | None
    createdAt: int
    participants: list[GroupParticipant]
    isReadOnly: bool
    isAnnounce: bool
    linkedParentJID: str | None


class CreateGroupRequest(TypedDict):
    name: str
    participants: list[Jid]


class InviteCodeResponse(TypedDict, total=False):
    inviteCode: str
    inviteLink: str
    message: str


# ── Webhook ───────────────────────────────────────────────────────


class WebhookFilterCondition(TypedDict):
    field: str
    operator: str
    value: list[str]


class WebhookFilters(TypedDict):
    conditions: list[WebhookFilterCondition]


class CreateWebhookRequest(TypedDict, total=False):
    url: str
    events: list[WebhookEvent]
    secret: str
    headers: dict[str, str]
    filters: WebhookFilters | None
    # Server DTO field is ``retryCount`` (0–5; default 3).
    retryCount: int


class UpdateWebhookRequest(CreateWebhookRequest, total=False):
    active: bool


class WebhookResponse(TypedDict, total=False):
    id: str
    sessionId: str
    url: str
    events: list[WebhookEvent]
    active: bool
    filters: WebhookFilters | None
    retryCount: int
    # ISO timestamp of the last delivery attempt, or None if never triggered.
    lastTriggeredAt: str | None
    createdAt: str
    updatedAt: str
    # NOTE: the server deliberately omits ``secret`` and ``headers`` from reads.


class WebhookTestResult(TypedDict, total=False):
    success: bool
    statusCode: int
    error: str


# ── Chat ──────────────────────────────────────────────────────────


class ChatSummary(TypedDict, total=False):
    id: Jid
    name: str | None
    isGroup: bool
    unreadCount: int
    # Server returns a plain preview string, not a message object.
    lastMessage: str
    timestamp: str | int


class MarkChatRequest(TypedDict):
    chatId: Jid


class SendChatStateRequest(TypedDict):
    chatId: Jid
    state: ChatState


class DeleteChatRequest(TypedDict):
    chatId: Jid


# ── Status / Stories ──────────────────────────────────────────────


class StatusRecord(TypedDict, total=False):
    id: str
    statusId: str
    type: str
    body: str | None
    timestamp: str | int


class SendTextStatusRequest(TypedDict, total=False):
    # text required; backgroundColor (hex, e.g. #25D366) and font optional.
    text: str
    backgroundColor: str
    font: int


class StatusMediaInput(TypedDict, total=False):
    """Media payload for a status post: provide ``url`` OR ``base64``."""

    url: str
    base64: str


class SendImageStatusRequest(TypedDict, total=False):
    """Server expects a nested ``{ image: { url|base64 } }`` body."""

    image: StatusMediaInput
    caption: str


class SendVideoStatusRequest(TypedDict, total=False):
    """Server expects a nested ``{ video: { url|base64 } }`` body."""

    video: StatusMediaInput
    caption: str


# ── Health ────────────────────────────────────────────────────────


class HealthResponse(TypedDict, total=False):
    status: str
    timestamp: str
    version: str


class HealthReadyResponse(TypedDict, total=False):
    status: str
    details: dict[str, str]


# ── Auth ──────────────────────────────────────────────────────────


class AuthValidateResponse(TypedDict, total=False):
    valid: bool
    role: str


# ── Template ──────────────────────────────────────────────────────


class TemplateRecord(TypedDict, total=False):
    id: str
    sessionId: str
    name: str
    body: str  # template body with {{variable}} placeholders
    header: str | None
    footer: str | None
    createdAt: str
    updatedAt: str


class CreateTemplateRequest(TypedDict, total=False):
    # name + body required; header/footer optional. Modeled total=False
    # (callers pass plain dicts); the backend validates the required fields.
    name: str
    body: str
    header: str
    footer: str


class UpdateTemplateRequest(TypedDict, total=False):
    name: str
    body: str
    header: str
    footer: str


# ── Label (WhatsApp Business) ─────────────────────────────────────


class LabelRecord(TypedDict, total=False):
    id: str
    name: str
    color: str
    colorHex: str


class AddLabelRequest(TypedDict):
    labelId: str


# ── Channel / Newsletter ──────────────────────────────────────────


class ChannelRecord(TypedDict, total=False):
    id: Jid
    name: str
    description: str | None
    subscriberCount: int
    pictureUrl: str | None
    role: str


class ChannelMessageQuery(TypedDict, total=False):
    """Max messages to return (default 50)."""

    limit: int


class SubscribeChannelRequest(TypedDict):
    inviteCode: str


# ── Catalog (Business) ────────────────────────────────────────────


class CatalogInfo(TypedDict, total=False):
    id: str
    name: str
    description: str | None
    productCount: int
    url: str


class CatalogProductsQuery(TypedDict, total=False):
    page: int
    limit: int


class CatalogProduct(TypedDict, total=False):
    id: str
    name: str
    description: str | None
    price: float
    currency: str
    priceFormatted: str
    imageUrl: str | None
    url: str
    isAvailable: bool
    retailerId: str


class ProductPagination(TypedDict):
    page: int
    limit: int
    total: int
    totalPages: int


class PaginatedProducts(TypedDict):
    """Paginated payload returned by ``GET /sessions/:id/catalog/products``."""

    products: list[CatalogProduct]
    pagination: ProductPagination


# chatId + productId required; body optional. Modeled total=False for 3.9 compat
# (callers pass plain dicts); the backend validates the required fields.
class SendProductRequest(TypedDict, total=False):
    chatId: Jid
    productId: str
    body: str


# chatId required; body optional. See SendProductRequest note.
class SendCatalogRequest(TypedDict, total=False):
    chatId: Jid
    body: str
